version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "11:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@types/node"
    versions:
    - 14.14.25
    - 14.14.27
    - 14.14.28
    - 14.14.30
    - 14.14.31
    - 14.14.32
    - 14.14.33
    - 14.14.34
    - 14.14.35
    - 14.14.36
    - 14.14.37
    - 14.14.39
    - 14.14.41
    - 15.0.0
  - dependency-name: sass
    versions:
    - 1.32.10
    - 1.32.11
    - 1.32.5
    - 1.32.7
    - 1.32.8
  - dependency-name: eslint
    versions:
    - 7.19.0
    - 7.20.0
    - 7.21.0
    - 7.22.0
    - 7.23.0
    - 7.24.0
  - dependency-name: y18n
    versions:
    - 4.0.1
    - 4.0.2
  - dependency-name: react-dev-utils
    versions:
    - 11.0.4
  - dependency-name: elliptic
    versions:
    - 6.5.4
  - dependency-name: "@types/react"
    versions:
    - 17.0.1
    - 17.0.2
    - 17.0.3
  - dependency-name: typescript
    versions:
    - 4.1.4
    - 4.1.5
    - 4.2.2
    - 4.2.3
  - dependency-name: react-scripts
    versions:
    - 4.0.2
  - dependency-name: "@emotion/styled"
    versions:
    - 11.1.5
  - dependency-name: "@emotion/react"
    versions:
    - 11.1.4
  - dependency-name: "@testing-library/react"
    versions:
    - 11.2.4
  - dependency-name: "@testing-library/user-event"
    versions:
    - 12.6.2
